// This file is automatically generated by Views and will be overwritten
// when the morpher runs. If you want to contribute to how it's generated, eg,
// improving the algorithms inside, etc, see this:
// https://github.com/viewstools/morph/blob/master/ensure-is-media.js

import { useMedia } from 'use-media'

let useIsMedia = () => {
  let mobile = useMedia({ minWidth: 0, maxWidth: 375 })
  let tablet = useMedia({ minWidth: 376, maxWidth: 1024 })
  let laptop = useMedia({ minWidth: 1025, maxWidth: 1280 })
  let desktop = useMedia({ minWidth: 1281 })

  return {
    mobile,
    tablet,
    laptop,
    desktop,
  }
}
export default useIsMedia
